# Immutable metadata generated by Build-Installer.ps1 for this artifact.

function Get-DuneBuildMetadataPath {
    $serverDir = $script:DuneServerDir
    if (-not $serverDir) { $serverDir = Split-Path -Parent $PSScriptRoot }
    return (Join-Path $serverDir 'build-metadata.json')
}

function Get-DuneBuildMetadata {
    $default = @{ commit = ''; prerelease = $false; present = $false }
    try {
        $path = Get-DuneBuildMetadataPath
        if (-not (Test-Path -LiteralPath $path)) { return $default }
        $obj = Get-Content -LiteralPath $path -Raw -Encoding UTF8 -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
        $commit = ([string]$obj.commit).Trim().ToLowerInvariant()
        if ($commit -notmatch '^[0-9a-f]{7,40}$') { $commit = '' }
        return @{ commit = $commit; prerelease = [bool]$obj.prerelease; present = $true }
    } catch {
        return $default
    }
}
